2021-09-28 10:51:47,659 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 3 hosts
2021-09-28 10:55:40,844 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 3 hosts
2021-09-28 10:58:35,848 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 3 hosts
2021-09-28 11:04:21,742 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 3 hosts
2021-09-28 11:05:08,539 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:06:24,482 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:10:48,983 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:11:19,993 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:11:42,843 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:12:01,061 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:12:07,831 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:12:20,919 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:12:31,756 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:12:40,010 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:13:01,321 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:13:25,637 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:14:21,734 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:14:34,656 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:14:47,947 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:14:55,430 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:17:33,736 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:31:25,150 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:33:22,944 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': 'interfaces'} on 3 hosts
2021-09-28 11:45:55,722 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show ip ospf neighbor'} on 3 hosts
2021-09-28 11:46:00,809 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\util.py", line 283, in retry_on_signal
    return function()
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir_netmiko\tasks\netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir_netmiko\connections\netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\cisco\cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 350, in __init__
    self._open()
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 355, in _open
    self.establish_connection()
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 957, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 10.18.10.66:22



2021-09-28 11:46:00,811 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\util.py", line 283, in retry_on_signal
    return function()
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir_netmiko\tasks\netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir_netmiko\connections\netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\cisco\cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 350, in __init__
    self._open()
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 355, in _open
    self.establish_connection()
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 957, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 10.18.10.71:22



2021-09-28 11:46:00,812 - nornir.core.task -    ERROR -      start() - Host 'R3': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\util.py", line 283, in retry_on_signal
    return function()
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir_netmiko\tasks\netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir_netmiko\connections\netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\cisco\cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 350, in __init__
    self._open()
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 355, in _open
    self.establish_connection()
  File "C:\Users\dmuel\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 957, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 10.18.10.72:22



2021-09-28 11:48:43,439 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show ip ospf neighbor'} on 3 hosts
